# Generated by Django 2.2.7 on 2019-11-14 20:07

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_footertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='footertext',
            name='address',
            field=wagtail.core.fields.RichTextField(default='evgenijgncar@gmail.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footertext',
            name='email',
            field=models.EmailField(default='evgenijgncar@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
