# Generated by Django 2.2.7 on 2019-11-15 09:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0006_auto_20191115_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Домашняя страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_about',
            field=models.ForeignKey(blank=True, help_text='Изображение на ссылке на страницу О нас', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_news',
            field=models.ForeignKey(blank=True, help_text='Изображение на ссылке на страницу Новости', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_works',
            field=models.ForeignKey(blank=True, help_text='Изображение на ссылке на страницу Проектов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='some_text',
            field=wagtail.core.fields.RichTextField(default='some'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_field',
            field=models.CharField(default='some', max_length=128),
            preserve_default=False,
        ),
    ]
