# Generated by Django 2.2.7 on 2019-11-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0007_auto_20191115_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_field', models.CharField(default=None, max_length=64)),
                ('image', models.ForeignKey(blank=True, help_text='Изображение на ссылке на страницу Проектов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.HomePage')),
            ],
            options={
                'verbose_name': 'Слайды',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
