# Generated by Django 2.2.7 on 2019-11-16 09:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0009_auto_20191115_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Изображение на слайде', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_field', models.CharField(blank=True, help_text='Оглавление перед главным текстом', max_length=128)),
                ('main_text', wagtail.core.fields.RichTextField(help_text='Главный текст о нашей компании')),
                ('image_text', wagtail.core.fields.RichTextField(help_text='Текст под фото')),
                ('image', models.ForeignKey(blank=True, help_text='Изображение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
            bases=('wagtailcore.page',),
        ),
    ]
