# Generated by Django 2.2.7 on 2019-11-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0010_auto_20191116_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_us_link',
            field=models.ForeignKey(blank=True, help_text='Выбрать страницу О компании', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Ссылка на страницу О компании'),
        ),
    ]
