# Generated by Django 2.2.7 on 2019-11-17 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0012_companyservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyServices',
            new_name='ServicePage',
        ),
    ]
