# Generated by Django 2.2.7 on 2019-11-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0013_auto_20191117_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='services_section',
            field=models.ForeignKey(blank=True, help_text='дополнительная секция для ссылок на предоставляемые услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Секция наших услуг'),
        ),
    ]
