# Generated by Django 2.2.7 on 2019-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='body',
        ),
        migrations.AlterField(
            model_name='footertext',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес компании', max_length=128),
        ),
    ]
