# Generated by Django 2.2.7 on 2019-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191117_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='latlng_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
